server:
  port: 8001
  servlet:
    context-path: /spring-graphql-repository

spring:
  graphql:
    path: /customers-graphql
    schema:
      printer:
        enabled: true
      locations: classpath:graphql/
    graphiql:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace

  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

